-- Seed: 60 prompts validados (10 por matéria), baseados em UNESCO AI CFT + BNCC
-- Rode no SQL Editor do Supabase depois de já ter feito login pelo menos uma vez no app
-- (o professor autor será identificado pelo seu e-mail de cadastro)

with autor as (
  select id from auth.users where email = 'glauberglauber84@gmail.com' limit 1
)
insert into prompts (autor_id, titulo, disciplina, ano, ferramenta, inclusivo, prompt)
select autor.id, v.titulo, v.disciplina, v.ano, v.ferramenta, v.inclusivo, v.prompt
from autor, (values

-- ═══ LÍNGUA PORTUGUESA ═══
('Roda de invenção de histórias', 'Língua Portuguesa', '1º ao 3º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Você é um assistente de escrita criativa para uma criança de [idade] anos. Faça 5 perguntas, uma de cada vez, para ajudá-la a inventar uma história curta (personagem, lugar, problema, solução, final). Não escreva a história por ela — só as perguntas, em linguagem simples.'),
('Diagnóstico de fluência leitora', 'Língua Portuguesa', '1º ao 2º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Liste 10 palavras com a sílaba "[sílaba, ex: BRA]" em ordem crescente de dificuldade, para eu usar numa atividade de leitura em voz alta com alunos em fase de alfabetização. Não inclua palavras fora do vocabulário infantil.'),
('Feedback de produção textual sem reescrever', 'Língua Portuguesa', '4º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Leia o texto do aluno a seguir e dê feedback em 3 tópicos: (1) o que está bom, (2) uma sugestão de melhoria estrutural, (3) uma pergunta que o provoque a expandir uma ideia. Não reescreva nenhuma parte do texto: [colar texto]'),
('Roteiro de debate oral', 'Língua Portuguesa', '6º ao 7º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie um roteiro de debate em sala sobre "[tema]", com 3 perguntas provocadoras para cada lado (a favor/contra) e 2 regras de escuta respeitosa. Não tome partido nem sugira "a resposta certa".'),
('Análise de gênero textual', 'Língua Portuguesa', '7º ao 8º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Explique as características do gênero "[carta do leitor / notícia / crônica]" em até 5 tópicos simples, com um exemplo curto e fictício. Não escreva o texto completo que o aluno deveria produzir.'),
('Correção ortográfica comentada', 'Língua Portuguesa', '3º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Aponte até 5 erros ortográficos no texto abaixo, explicando a regra de cada um em uma frase, sem corrigir o texto inteiro nem reescrevê-lo: [colar texto]'),
('Preparação para redação dissertativa', 'Língua Portuguesa', '9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sobre o tema "[tema]", gere 4 perguntas que ajudem o aluno a organizar tese, 2 argumentos e uma proposta de intervenção — sem escrever nenhuma frase da redação.'),
('Leitura inclusiva adaptada', 'Língua Portuguesa', '1º ao 3º ano', 'ChatGPT, Gemini ou Copilot', true,
 'Reescreva o texto abaixo em frases curtas (máximo 8 palavras), vocabulário simples e sem duplo sentido, mantendo a ideia principal, para um aluno com dificuldade de leitura: [colar texto]'),
('Jogo de sinônimos e antônimos', 'Língua Portuguesa', '2º ao 4º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie 8 pares de palavras (sinônimo/antônimo) usando vocabulário do cotidiano de uma criança de [idade] anos, em formato de lista para eu imprimir como jogo de cartas.'),
('Análise crítica de notícia', 'Língua Portuguesa', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Apresente 5 perguntas que ajudem o aluno a avaliar se uma notícia é confiável (fonte, data, autor, viés, evidências) — sem dizer se a notícia específica que ele vai analisar é verdadeira ou falsa.'),

-- ═══ MATEMÁTICA ═══
('Tutor socrático de frações', 'Matemática', '4º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Aja como tutor de matemática. Quando eu enviar uma questão sobre frações, responda só com 2 perguntas que ajudem o aluno a pensar no caminho da solução — nunca dê a resposta direta.'),
('Problemas contextualizados do cotidiano', 'Matemática', '3º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie 5 problemas de matemática com operações de adição e subtração, ambientados em situações do dia a dia de uma criança de [idade] anos (mercado, escola, brincadeiras), com dificuldade crescente.'),
('Raciocínio geométrico guiado', 'Matemática', '6º ao 7º ano', 'ChatGPT, Gemini ou Copilot', false,
 'O aluno vai descrever uma figura geométrica que precisa calcular a área. Faça perguntas que o levem a identificar a fórmula certa, sem informar a fórmula diretamente.'),
('Erros comuns em equações', 'Matemática', '7º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Liste os 5 erros mais comuns que alunos cometem ao resolver equações de 1º grau, com um exemplo de cada erro e uma pergunta que ajude o aluno a perceber o próprio erro (sem corrigir por ele).'),
('Jogo de tabuada investigativo', 'Matemática', '2º ao 4º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie um jogo de perguntas e respostas sobre a tabuada do [número], em formato de desafio com pistas, para uma turma de [idade] anos.'),
('Interpretação de gráficos', 'Matemática', '5º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'A partir da descrição de um gráfico de barras que vou te dar, gere 4 perguntas de interpretação de diferentes níveis (leitura direta, comparação, inferência), sem responder nenhuma delas.'),
('Raciocínio lógico com blocos', 'Matemática', '1º ao 2º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sugira uma sequência de 3 desafios com blocos de montar ou material concreto para trabalhar padrões e sequências lógicas com crianças de [idade] anos, do mais fácil ao mais difícil.'),
('Matemática financeira acessível', 'Matemática', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', true,
 'Explique o conceito de juros simples com uma analogia do cotidiano, usando frases curtas e um exemplo numérico simples, adequado para aluno com dificuldade de processamento de texto longo.'),
('Verificação de hipóteses matemáticas', 'Matemática', '6º ao 8º ano', 'ChatGPT, Gemini ou Copilot', false,
 'O aluno propôs a hipótese "[hipótese]" sobre um padrão numérico. Sugira 3 perguntas para ele testar se a hipótese é sempre verdadeira, sem confirmar ou negar diretamente.'),
('Resolução de problemas em duplas', 'Matemática', '3º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie um problema matemático de várias etapas que só pode ser resolvido se duas crianças trocarem informações diferentes entre si (uma sabe uma parte do dado, a outra sabe outra parte).'),

-- ═══ CIÊNCIAS ═══
('Orientador de experimento com hipóteses', 'Ciências', '6º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Atue como orientador de um experimento científico. Ajude o aluno a formular uma hipótese testável sobre "[fenômeno]", listar materiais e sugerir como registrar resultados. Não execute o experimento por ele nem revele o resultado esperado.'),
('Perguntas sobre o corpo humano', 'Ciências', '4º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Gere 6 perguntas investigativas sobre o sistema [digestório/respiratório/circulatório] adequadas para uma criança de [idade] anos, que estimulem observação do próprio corpo, sem dar as respostas.'),
('Simulação de método científico', 'Ciências', '7º ao 8º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Descreva um fenômeno cotidiano relacionado a "[tema, ex: mudanças de estado da água]" e peça ao aluno para propor uma explicação, antes de você complementar com informações adicionais.'),
('Observação da natureza', 'Ciências', '1º ao 3º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sugira uma atividade de observação ao ar livre (pátio da escola ou quintal) sobre "[plantas/insetos/tempo]" com 3 perguntas guiadas para a criança registrar o que observou, em linguagem simples.'),
('Debate sobre sustentabilidade', 'Ciências', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Apresente 2 perspectivas diferentes sobre "[tema ambiental]" de forma equilibrada, e gere 4 perguntas que ajudem o aluno a formar sua própria opinião com base em evidências, sem impor um lado.'),
('Explicação adaptada para NEE', 'Ciências', '5º ao 6º ano', 'ChatGPT, Gemini ou Copilot', true,
 'Explique o conceito de "[fotossíntese/ciclo da água]" usando uma analogia visual simples e frases curtas, para um aluno com deficiência intelectual leve, evitando termos técnicos sem explicação.'),
('Classificação de seres vivos', 'Ciências', '2º ao 4º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie um jogo de classificação com 10 seres vivos (animais/plantas conhecidos por crianças) para elas agruparem por características, sem dizer a resposta certa — só as pistas.'),
('Análise de dados de experimento', 'Ciências', '7º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'A partir da tabela de resultados que vou descrever, gere perguntas que ajudem o aluno a identificar padrões e possíveis erros experimentais, sem tirar a conclusão por ele.'),
('Ciclo de vida ilustrado', 'Ciências', '1º ao 2º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Descreva em 4 etapas simples o ciclo de vida de uma borboleta, em frases curtas para eu transformar em cartazes ilustrados com a turma.'),
('Questionamento sobre tecnologia e IA', 'Ciências', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Gere 5 perguntas que ajudem os alunos a refletir criticamente sobre como a Inteligência Artificial funciona e onde ela pode errar, sem usar jargão técnico.'),

-- ═══ ARTES ═══
('Referências visuais antes de criar', 'Artes', '4º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Liste 4 artistas ou movimentos artísticos relacionados a "[tema/técnica]" com uma frase de contexto histórico de cada um, para os alunos pesquisarem antes de criar sua própria obra.'),
('Roteiro de apreciação de obra', 'Artes', '3º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie um roteiro de 5 perguntas para os alunos observarem e discutirem uma obra de arte (cores, formas, sentimento, contexto), sem dizer o que a obra "significa".'),
('Inspiração musical rítmica', 'Artes', '1º ao 3º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sugira uma atividade simples de percussão corporal (palmas, pés) em 3 níveis de dificuldade para trabalhar ritmo com crianças de [idade] anos.'),
('Crédito e autoria com IA', 'Artes', '7º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Gere 3 perguntas para uma roda de conversa sobre "quando a IA participa de uma criação artística, quem é o autor?" — apresentando argumentos dos dois lados, sem dar uma resposta fechada.'),
('Teatro e expressão corporal', 'Artes', '5º ao 7º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie 4 exercícios curtos de expressão corporal sem fala para os alunos representarem emoções, adequados para uma turma que nunca fez teatro antes.'),
('Análise de cores e emoções', 'Artes', '2º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Explique de forma simples como certas cores costumam ser associadas a certas emoções em diferentes culturas (evite estereótipos), e sugira uma atividade de pintura livre sobre um sentimento.'),
('Adaptação para aluno com baixa visão', 'Artes', '1º ao 9º ano', 'ChatGPT, Gemini ou Copilot', true,
 'Sugira 3 adaptações de uma atividade de desenho livre para incluir um aluno com baixa visão, priorizando texturas e materiais táteis.'),
('Dança e cultura brasileira', 'Artes', '6º ao 8º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Liste 4 danças populares brasileiras de regiões diferentes, com uma característica marcante de cada uma, para os alunos escolherem uma e pesquisarem sua origem cultural.'),
('Criação de história em quadrinhos', 'Artes', '4º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sugira uma estrutura de 6 quadros para uma história em quadrinhos sobre "[tema]", com perguntas norteadoras para cada quadro — sem escrever os diálogos.'),
('Reflexão sobre arte gerada por IA', 'Artes', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Gere 4 perguntas para os alunos compararem uma obra feita por humano e uma gerada por IA, sobre técnica, intenção e originalidade — sem dizer qual é "melhor".'),

-- ═══ HISTÓRIA ═══
('Investigação de fontes históricas', 'História', '6º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Apresente 2 fontes históricas fictícias (ou que vou colar) sobre "[evento]" com pontos de vista diferentes, e gere 4 perguntas para o aluno comparar as versões, sem dizer qual é "mais correta".'),
('Linha do tempo guiada', 'História', '4º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Liste 6 eventos-chave sobre "[período histórico]" em ordem cronológica, cada um com uma frase simples, para os alunos montarem uma linha do tempo ilustrada.'),
('Perguntas sobre a própria história', 'História', '1º ao 3º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie 5 perguntas simples para a criança entrevistar um familiar mais velho sobre "como era a infância dele/dela", trabalhando noção de tempo e memória.'),
('Debate sobre múltiplas narrativas', 'História', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sobre "[tema histórico controverso]", apresente 2 ou mais narrativas historiográficas diferentes de forma equilibrada, com uma pergunta final que provoque o aluno a formar opinião com base em evidências.'),
('Cultura e ancestralidade', 'História', '5º ao 7º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sugira 3 fontes confiáveis (livros, documentários, museus virtuais) sobre a cultura de um povo indígena ou afro-brasileiro específico, com uma pergunta de reflexão para cada uma.'),
('Simulação de tomada de decisão histórica', 'História', '7º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Descreva um dilema que uma pessoa comum viveria durante "[evento histórico]" e peça para o aluno decidir o que faria, justificando com o contexto da época — sem dizer a "decisão certa".'),
('Comparação passado-presente', 'História', '3º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Gere 4 perguntas comparando como era "[tema, ex: escola/brincadeiras/transporte]" há 50 anos e hoje, para uma conversa em roda com a turma.'),
('Análise de imagem histórica', 'História', '6º ao 8º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie um roteiro de 5 perguntas para os alunos analisarem uma imagem/pintura histórica (o que veem, quem está presente, o que está ausente, de que época pode ser).'),
('Mapa mental de causas e consequências', 'História', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Para o evento "[evento histórico]", gere 3 perguntas que ajudem o aluno a distinguir causas imediatas de causas estruturais, sem listar as causas por ele.'),
('Adaptação simplificada de texto histórico', 'História', '4º ao 5º ano', 'ChatGPT, Gemini ou Copilot', true,
 'Reescreva o texto histórico abaixo em frases curtas e vocabulário simples, mantendo os fatos, para um aluno com dificuldade de leitura: [colar texto]'),

-- ═══ GEOGRAFIA ═══
('Leitura de mapas guiada', 'Geografia', '4º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Descreva as informações de um mapa que vou te passar e gere 4 perguntas de interpretação (localização, distância, legenda), sem responder por mim.'),
('Meu lugar no mundo', 'Geografia', '1º ao 3º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Crie 5 perguntas simples para a criança descrever seu bairro/cidade (o que tem perto de casa, como vai pra escola), trabalhando noção de espaço vivido.'),
('Mudanças climáticas com equilíbrio', 'Geografia', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Explique de forma acessível o que é o efeito estufa, com uma analogia simples, e gere 3 perguntas para os alunos discutirem soluções locais, sem impor uma posição política.'),
('Comparação de paisagens', 'Geografia', '3º ao 5º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Descreva 3 tipos de paisagem brasileira (litoral, sertão, floresta) com uma característica marcante de cada, para os alunos compararem em um quadro comparativo.'),
('Urbanização e desigualdade', 'Geografia', '7º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Apresente dados fictícios (ou que vou colar) sobre crescimento urbano de uma cidade, e gere 4 perguntas que levem o aluno a refletir sobre desigualdade socioespacial, sem dar conclusões prontas.'),
('Orientação espacial com bússola', 'Geografia', '5º ao 6º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Sugira uma atividade prática no pátio da escola para ensinar pontos cardeais usando sombra do sol ou bússola, com 3 desafios de dificuldade crescente.'),
('Globalização no cotidiano', 'Geografia', '8º ao 9º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Peça para o aluno listar 5 objetos que ele usa e pesquisar de onde vêm; gere perguntas que o ajudem a perceber conexões globais, sem fornecer as respostas prontas.'),
('Recursos naturais da região', 'Geografia', '4º ao 7º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Liste 3 perguntas investigativas sobre os recursos naturais da região onde a escola está localizada, para pesquisa em grupo.'),
('Mapa mental adaptado', 'Geografia', '4º ao 6º ano', 'ChatGPT, Gemini ou Copilot', true,
 'Sugira uma versão tátil/simplificada de uma atividade de leitura de mapa para um aluno com baixa visão, priorizando descrição verbal detalhada.'),
('Migração e diversidade', 'Geografia', '6º ao 8º ano', 'ChatGPT, Gemini ou Copilot', false,
 'Gere 4 perguntas para uma roda de conversa sobre por que pessoas migram, com exemplos neutros e sem estereotipar nenhum grupo migrante.')

) as v(titulo, disciplina, ano, ferramenta, inclusivo, prompt);
