-- Seed: glossário de ferramentas de IA para professores
-- Gerado a partir de GLOSSÁRIO IA.docx
insert into glossario (nome, categoria, descricao) values
('Adobe Express AI', 'Diversas', 'Produz apresentações, cartazes e vídeos educativos.'),
('Adobe Firefly', 'Diversas', 'IA para criação e edição de imagens para atividades pedagógicas.'),
('AI Dungeon', 'Diversas', 'Jogo narrativo baseado em IA para criação de histórias e produção textual.'),
('AI Music Generator', 'Diversas', 'Cria músicas educativas.'),
('AI Quiz Generator', 'Diversas', 'Produz questionários automaticamente.'),
('Almanack AI', 'Diversas', 'Plataforma de planejamento de aulas utilizando IA.'),
('Animated Drawings', 'Diversas', 'Anima desenhos feitos pelos alunos usando IA.'),
('ArcGIS AI', 'Geografia', 'mapas inteligentes e análise de dados geográficos.'),
('AskYourPDF', 'Diversas', 'Conversa com PDFs para estudar documentos e artigos.'),
('AudioPen', 'Diversas', 'Transforma fala em textos organizados.'),
('AutoDraw', 'Diversas', 'Desenhos inteligentes do Google para criar materiais visuais.'),
('Bardeen AI', 'Automação', 'Automatiza tarefas repetitivas como organização de documentos, coleta de informações, preenchimento de planilhas e integração entre aplicativos.'),
('Beautiful.ai', 'Apresentações', 'Plataforma que utiliza IA para criar apresentações profissionais automaticamente, organizando layouts e design dos slides.'),
('Bing Copilot', 'Ciências', 'pesquisa científica com suporte de IA.'),
('Bing Image Creator (Microsoft Designer)', 'Geração de imagens', 'Cria imagens por IA a partir de comandos em texto. Excelente para ilustrar aulas, produzir atividades e materiais didáticos.'),
('Blackbox AI', 'Programação', 'Assistente de programação baseado em IA que auxilia professores e estudantes na criação, explicação e correção de códigos em diversas linguagens.'),
('BlueWillow AI', 'Geração de imagens', 'Plataforma gratuita para criação de imagens por inteligência artificial, útil para produção de ilustrações educativas.'),
('BoodleBox AI', 'Colaboração', 'Ambiente colaborativo onde diversas IAs trabalham juntas para brainstorming, planejamento de aulas e projetos escolares.'),
('Book Creator AI', 'Produção de livros', 'Permite criar livros digitais interativos com auxílio da IA, incluindo textos, imagens, áudio e vídeos produzidos pelos estudantes.'),
('Botpress', 'Criação de chatbots', 'Plataforma que permite desenvolver chatbots inteligentes para atendimento escolar, projetos de programação e aprendizagem sobre IA.'),
('Brainly AI (Brainly Tutor)', 'Apoio ao estudo', 'Assistente inteligente que explica exercícios, responde dúvidas e auxilia estudantes na aprendizagem de diversas disciplinas.'),
('Brisk Teaching', 'Educação', 'Extensão para professores que cria planos de aula, feedbacks, rubricas, questões e adapta atividades diretamente no navegador.'),
('Canva AI', 'História', 'criação de linhas do tempo e infográficos históricos.'),
('Canva Magic Design', 'Arte', 'criação de materiais visuais com IA.'),
('Canva Magic Studio', 'Design e apresentações', 'Conjunto de ferramentas de IA do Canva que cria apresentações, imagens, vídeos, planos de aula e materiais didáticos a partir de comandos em texto.'),
('Character.AI', 'Simulação de personagens', 'Permite conversar com personagens históricos, cientistas, escritores ou personagens fictícios, favorecendo atividades de interpretação, história e literatura.'),
('ChatGPT', 'Assistente educacional', 'IA conversacional que auxilia na elaboração de planos de aula, atividades, avaliações, rubricas, textos, projetos, adaptações curriculares e explicações de conteúdos.'),
('Claude AI', 'Assistente de escrita', 'IA especializada em leitura, análise e produção de textos longos, excelente para revisar documentos, elaborar sequências didáticas e resumir materiais.'),
('Codeium', 'Programação', 'Assistente de programação por IA que ajuda professores e estudantes na escrita, explicação e correção de códigos.'),
('Consensus', 'Pesquisa científica', 'Ferramenta de busca baseada em IA que localiza evidências científicas em artigos acadêmicos, facilitando pesquisas educacionais e fundamentação teórica.'),
('Copilot (Microsoft Copilot)', 'Produtividade', 'Assistente de IA integrado ao Microsoft 365 que auxilia na criação de documentos, apresentações, planilhas, e-mails e planejamento pedagógico.'),
('Coursebox AI', 'Criação de cursos', 'Plataforma que utiliza IA para desenvolver cursos completos, incluindo conteúdos, avaliações, atividades e materiais digitais.'),
('Craiyon', 'Geração de imagens', 'Ferramenta gratuita que cria ilustrações por inteligência artificial a partir de descrições em texto, útil para materiais pedagógicos.'),
('Curipod', 'Aulas interativas', 'Plataforma que gera apresentações, perguntas, enquetes, debates e atividades interativas utilizando inteligência artificial.'),
('DALL·E', 'Geração de imagens', 'IA da OpenAI que cria imagens a partir de descrições em texto, ideal para ilustrar aulas, histórias, experimentos e materiais didáticos.'),
('Decktopus AI', 'Apresentações', 'Cria apresentações automaticamente com design profissional, sugestões de conteúdo e recursos visuais voltados para aulas e palestras.'),
('DeepL Translator', 'Tradução', 'Traduz textos com alta precisão entre diversos idiomas, auxiliando professores na adaptação de materiais e pesquisas internacionais.'),
('DeepL Write', 'Escrita e revisão', 'Ferramenta que utiliza IA para revisar textos, melhorar a clareza, corrigir gramática e sugerir diferentes estilos de escrita.'),
('Descript', 'Áudio e vídeo', 'Editor de áudio e vídeo baseado em IA que permite editar gravações como se fossem um documento de texto, facilitando a criação de videoaulas e podcasts.'),
('D-ID', 'Avatares e vídeos', 'Plataforma que cria vídeos com avatares falantes a partir de textos, sendo útil para apresentações, explicações de conteúdos e aulas acessíveis.'),
('Diffit', 'Planejamento pedagógico', 'Plataforma que adapta textos para diferentes níveis de leitura e gera automaticamente perguntas, atividades e vocabulário para os estudantes.'),
('DocAnalyzer AI', 'Análise de documentos', 'Permite conversar com documentos em PDF, Word e outros formatos, resumindo conteúdos, respondendo perguntas e identificando informações importantes.'),
('Doctrina AI', 'Educação', 'Ferramenta que gera resumos, questionários, provas, flashcards e materiais de estudo personalizados para diferentes disciplinas.'),
('Dream by WOMBO', 'Geração de imagens', 'Plataforma de IA que transforma descrições textuais em ilustrações artísticas para projetos escolares, cartazes e atividades.'),
('Duolingo Max (IA)', 'Inglês', 'conversação e explicações inteligentes.'),
('Easy-Peasy.AI', 'Criação de conteúdo', 'Plataforma multifuncional que produz textos, imagens, transcrições, resumos, apresentações e outros conteúdos com auxílio da inteligência artificial.'),
('Edcafe AI', 'Organização educacional', 'Plataforma que reúne ferramentas para criar atividades, organizar conteúdos, compartilhar materiais e utilizar diversos recursos de IA em um único ambiente.'),
('EdPuzzle AI', 'Videoaulas', 'Utiliza IA para gerar automaticamente perguntas, quizzes e atividades a partir de vídeos educativos, tornando as aulas mais interativas.'),
('Eduaide.AI', 'Planejamento pedagógico', 'Plataforma desenvolvida para professores que cria planos de aula, avaliações, rubricas, atividades diferenciadas, feedbacks e adaptações curriculares com IA.'),
('Education Copilot', 'Planejamento de aulas', 'Gera planos de aula, atividades, objetivos de aprendizagem, avaliações e materiais pedagógicos em poucos minutos.'),
('Elastic (Elastic Search AI)', 'Busca inteligente', 'Sistema de busca com IA capaz de localizar rapidamente informações em grandes bancos de documentos escolares, institucionais ou acadêmicos.'),
('ElevenLabs', 'Síntese de voz', 'Converte textos em áudios com vozes naturais em diversos idiomas, sendo ideal para produção de audiolivros, podcasts, videoaulas e recursos de acessibilidade.'),
('Elicit', 'Pesquisa científica', 'Assistente de IA que localiza, resume e compara artigos científicos, auxiliando professores em pesquisas acadêmicas e revisão de literatura.'),
('Elsa Speak', 'Inglês', 'pronúncia e fluência oral com IA.'),
('EssayGrader AI', 'Correção de redações', 'Ferramenta que avalia redações automaticamente, fornecendo feedback detalhado sobre escrita, gramática, organização e argumentação.'),
('Explainpaper', 'Leitura acadêmica', 'Simplifica artigos científicos, explicando trechos complexos em linguagem acessível, facilitando estudos e pesquisas docentes.'),
('Fathom AI', 'Reuniões', 'Grava, transcreve e resume reuniões automaticamente, facilitando registros de encontros pedagógicos, conselhos de classe e formações.'),
('Fetchy', 'Assistente para professores', 'Ferramenta desenvolvida para reduzir o trabalho administrativo dos docentes, criando planos de aula, e-mails, atividades, feedbacks e comunicados.'),
('FigJam AI', 'Colaboração', 'Recurso de IA da plataforma FigJam que auxilia na criação de mapas mentais, brainstorming, planejamentos e organização de projetos colaborativos.'),
('Filmora AI', 'Edição de vídeos', 'Editor de vídeos com recursos de IA, como remoção de ruído, legendas automáticas, geração de roteiros e edição inteligente para produção de aulas.'),
('Firefly (Adobe Firefly)', 'Geração de imagens', 'IA da Adobe para criar e editar imagens, aplicar efeitos, preencher áreas de fotos e produzir ilustrações para materiais didáticos.'),
('Fitbod AI', 'Educação Física', 'criação de treinos personalizados.'),
('FlexClip AI', 'Produção de vídeos', 'Plataforma que utiliza IA para criar e editar vídeos, legendas automáticas, narrações e apresentações para aulas.'),
('Fliki AI', 'Texto para vídeo', 'Converte textos em vídeos narrados com vozes realistas, ideal para videoaulas, explicações e conteúdos para ensino híbrido.'),
('FlowGPT', 'Biblioteca de prompts', 'Comunidade que reúne milhares de prom'),
('Fobizz AI', 'Formação docente', 'Plataforma voltada para educadores que reúne diversas ferramentas de IA para criar planos de aula, atividades, imagens, quizzes e recursos digitais.'),
('Forms.app AI', 'Formulários e avaliações', 'Gera automaticamente formulários, questionários, pesquisas e avaliações personalizadas utilizando inteligência artificial.'),
('Freeletics AI Coach', 'Educação Física', 'planos de treino adaptativos.'),
('Gamma', 'Apresentações', 'Plataforma que cria apresentações, documentos e páginas interativas automaticamente a partir de comandos em texto, com design profissional.'),
('Gemini (Google)', 'Assistente de IA', 'IA generativa do Google que auxilia na criação de planos de aula, atividades, textos, pesquisas, programação e análise de documentos, integrada ao ecossistema Google Workspace.'),
('Genially AI', 'Conteúdo interativo', 'Utiliza recursos de IA para facilitar a criação de apresentações, jogos, infográficos, escape rooms e atividades gamificadas.'),
('GeoGebra', 'Matemática', 'geometria dinâmica e álgebra visual.'),
('GitHub Copilot', 'Programação', 'Assistente de programação baseado em IA que sugere códigos, explica algoritmos e auxilia professores e estudantes em projetos de computação.'),
('Gizmo (antigo Save All)', 'Flashcards', 'Plataforma que utiliza IA para transformar anotações, PDFs e textos em flashcards inteligentes e questionários para revisão de conteúdos.'),
('Glasp AI', 'Leitura e pesquisa', 'Permite destacar trechos de páginas da web e vídeos, organizando resumos e utilizando IA para sintetizar conteúdos importantes.'),
('Google AI Studio', 'Desenvolvimento de IA', 'Ambiente para testar e criar aplicações utilizando os modelos Gemini, útil para projetos educacionais, programação e experimentação com IA.'),
('Google Earth AI', 'Geografia', 'exploração geográfica e análise espacial.'),
('Google Fit (IA de monitoramento)', 'Educação Física', 'análise de atividade física.'),
('Google NotebookLM', 'Pesquisa e estudo', 'Assistente de IA do Google que analisa documentos enviados pelo usuário, gera resumos, responde perguntas e organiza conteúdos para estudo e planejamento docente.'),
('Google Science Journal (com IA integrada)', 'Ciências', 'observação e análise de fenômenos.'),
('Grammarly', 'Escrita e revisão', 'Ferramenta de IA que corrige ortografia, gramática, estilo e clareza de textos em inglês, auxiliando professores e estudantes na produção escrita.'),
('Grok', 'Assistente de IA', 'IA conversacional desenvolvida pela xAI que responde perguntas, auxilia em pesquisas, gera textos, explica conceitos e apoia atividades educacionais e criativas.'),
('Hailuo AI', 'Geração de vídeos', 'Ferramenta que transforma textos e imagens em vídeos curtos com auxílio de IA, útil para produção de conteúdos educacionais e explicações visuais.'),
('Hedra AI', 'Avatares falantes', 'Plataforma que cria personagens animados capazes de falar e expressar emoções a partir de textos ou gravações, tornando as aulas mais envolventes.'),
('HeyGen', 'Avatares e vídeos', 'Plataforma de IA que cria vídeos com avatares realistas, tradução automática de voz e sincronização labial, ideal para videoaulas e apresentações.'),
('History AI tools (ex: TimeMaps AI)', 'História', 'linhas do tempo interativas.'),
('HIX AI', 'Produção de conteúdo', 'Assistente de IA que gera textos, resumos, e-mails, planejamentos, traduções e revisões, apoiando a produção de materiais pedagógicos.'),
('Homeworkify AI', 'Apoio aos estudos', 'Ferramenta que explica exercícios e apresenta resoluções comentadas, podendo ser utilizada pelos professores para demonstrar diferentes estratégias de resolução. Seu uso deve ser acompanhado para evitar dependência dos alunos.'),
('Hotpot AI', 'Design gráfico', 'Plataforma que cria imagens, ilustrações, restaura fotografias, remove fundos e produz materiais gráficos para uso em sala de aula.'),
('Hour One AI', 'Produção de videoaulas', 'Gera vídeos com apresentadores virtuais realistas, permitindo criar aulas, treinamentos e comunicados sem necessidade de gravação presencial.'),
('Hugging Face', 'Modelos de IA', 'Plataforma que reúne milhares de modelos de inteligência artificial para processamento de linguagem, imagens, áudio e visão computacional, muito utilizada em pesquisa e educação.'),
('Humata AI', 'Análise de documentos', 'Permite conversar com arquivos em PDF, Word e outros documentos, respondendo perguntas, gerando resumos e localizando informações importantes para estudos e planejamento.'),
('HyperWrite AI', 'Escrita', 'Assistente de escrita que auxilia na elaboração de textos, planos de aula, e-mails, atividades e feedbacks personalizados.'),
('Ideogram AI', 'Geração de imagens', 'Plataforma de IA especializada na criação de imagens com excelente renderização de textos, ideal para cartazes, infográficos e materiais didáticos.'),
('iLovePDF AI', 'Documentos', 'Utiliza IA para resumir, organizar e interagir com arquivos PDF, além de oferecer ferramentas para edição, conversão e gerenciamento de documentos.'),
('ImageFX (Google)', 'Geração de imagens', 'IA do Google para criar imagens realistas e artísticas a partir de descrições em texto, útil na elaboração de recursos visuais para aulas.'),
('Immersity AI', 'Conteúdo imersivo', 'Plataforma que converte imagens e vídeos em experiências 3D e com efeitos de profundidade, tornando conteúdos educacionais mais envolventes.'),
('Ink AI (INK Editor)', 'Escrita e SEO', 'Assistente de escrita que auxilia na produção e revisão de textos, oferecendo sugestões de clareza, organização e otimização de conteúdo.'),
('Intelliboard', 'Análise de aprendizagem', 'Plataforma de análise de dados educacionais que utiliza IA para acompanhar o desempenho dos estudantes, identificar dificuldades e gerar relatórios.'),
('Interacty', 'Atividades interativas', 'Plataforma que cria jogos, quizzes, apresentações e atividades interativas com apoio de IA, favorecendo metodologias ativas e aprendizagem gamificada.'),
('InVideo AI', 'Produção de vídeos', 'Ferramenta que transforma textos e roteiros em vídeos completos com narração, imagens, legendas e trilha sonora, facilitando a criação de videoaulas.'),
('Inworld AI', 'Personagens inteligentes', 'Permite criar personagens virtuais capazes de conversar em tempo real, sendo útil para simulações, jogos educativos e atividades de aprendizagem baseada em problemas.'),
('Iris.ai', 'Pesquisa científica', 'Ferramenta que utiliza IA para localizar, organizar e sintetizar artigos científicos, facilitando revisões de literatura e pesquisas acadêmicas.'),
('Jamboard AI (Google Workspace)', 'Colaboração', 'Recursos de IA integrados ao ambiente colaborativo do Google para organizar ideias, brainstormings e atividades em grupo. (Observação: o Jamboard foi descontinuado, mas seus recursos migraram para outras plataformas do Google Workspace.)'),
('Jammable AI', 'Produção de áudio', 'Ferramenta que utiliza IA para criar narrações e versões musicais, podendo ser empregada em projetos de produção de podcasts e atividades criativas.'),
('Jasper AI', 'Produção de conteúdo', 'Ferramenta de IA para criação de textos, planos de aula, comunicados, roteiros, atividades e materiais educativos.'),
('Jenni AI', 'Escrita acadêmica', 'Assistente de escrita baseado em IA que auxilia na produção de artigos, projetos, relatórios, referências e textos acadêmicos.'),
('JigsawStack AI', 'Desenvolvimento de aplicações', 'Plataforma que oferece APIs baseadas em IA para criação de recursos como OCR, reconhecimento de imagens e processamento de documentos, útil em projetos de tecnologia educacional.'),
('Jobright AI', 'Orientação profissional', 'Plataforma que auxilia na exploração de carreiras e competências, podendo ser utilizada em projetos de orientação profissional com estudantes do Ensino Fundamental e Médio.'),
('Jotform AI', 'Formulários e avaliações', 'Plataforma que utiliza IA para criar formulários, questionários, pesquisas e avaliações automaticamente, facilitando a coleta e análise de respostas dos estudantes.'),
('Journey AI', 'Apresentações', 'Plataforma que cria apresentações e documentos com auxílio da inteligência artificial, organizando conteúdos e elementos visuais automaticamente.'),
('JoySchooler AI', 'Educação', 'Assistente voltado para professores que gera atividades, avaliações, planos de aula e sugestões metodológicas personalizadas.'),
('Julius AI', 'Análise de dados', 'Ferramenta que interpreta planilhas, cria gráficos, realiza análises estatísticas e responde perguntas sobre dados utilizando linguagem natural.'),
('Kahoot! AI', 'Gamificação', 'Recurso de IA do Kahoot! que cria quizzes, perguntas e jogos educativos automaticamente a partir de textos, PDFs ou tópicos.'),
('Keyword Insights AI', 'Organização de conteúdo', 'Ferramenta que utiliza IA para organizar palavras-chave e temas relacionados, auxiliando professores na elaboração de projetos, pesquisas e sequências didáticas.'),
('Khanmigo', 'Tutor inteligente', 'Assistente de IA da Khan Academy que apoia professores e estudantes com explicações, planejamento de aulas, elaboração de atividades e acompanhamento da aprendizagem.'),
('Kickresume AI', 'Escrita profissional', 'IA que auxilia na elaboração de currículos, cartas de apresentação e perfis profissionais, podendo ser utilizada em projetos de orientação profissional com estudantes.'),
('Kipper AI', 'Apoio aos estudos', 'Assistente de IA voltado para estudantes e professores, capaz de gerar resumos, explicações, quizzes e materiais de revisão. Seu uso deve ser acompanhado para incentivar a aprendizagem crítica.'),
('Kling AI', 'Geração de vídeos', 'Ferramenta de IA capaz de criar vídeos realistas a partir de textos ou imagens, útil para produção de materiais audiovisuais educativos.'),
('Knowt AI', 'Flashcards e estudo', 'Plataforma que transforma anotações, PDFs e apresentações em flashcards, resumos e quizzes para revisão de conteúdos.'),
('Komo AI', 'Pesquisa inteligente', 'Mecanismo de busca baseado em IA que organiza resultados, responde perguntas e apresenta informações de forma sintetizada, facilitando pesquisas escolares.'),
('Konjer AI', 'Leitura interativa', 'Plataforma que permite interagir com livros digitais utilizando IA, respondendo perguntas, explicando conceitos e aprofundando a compreensão textual.'),
('Krea AI', 'Geração de imagens', 'Plataforma para criar e editar imagens em tempo real com inteligência artificial, permitindo desenvolver ilustrações, cartazes e recursos visuais para aulas.'),
('Labster AI', 'Ciências', 'simulações de laboratório virtual.'),
('LanguageTool', 'Língua Portuguesa', 'correção gramatical e ortográfica avançada.'),
('LanguageTool AI', 'Revisão de textos', 'Assistente de escrita que corrige ortografia, gramática, pontuação e estilo em diversos idiomas, incluindo português.'),
('LearnAbout AI (Google)', 'Aprendizagem', 'Recurso experimental do Google que utiliza IA para explicar conceitos, responder perguntas e adaptar explicações ao nível do estudante.'),
('Leonardo AI', 'Geração de imagens', 'Plataforma de IA para criar ilustrações, personagens, infográficos e recursos visuais de alta qualidade para materiais didáticos.'),
('LessonPlans.ai', 'Planejamento pedagógico', 'Plataforma que gera planos de aula completos, objetivos de aprendizagem, metodologias e atividades alinhadas às necessidades do professor.'),
('LessonUp AI', 'Aulas interativas', 'Ferramenta que cria apresentações, quizzes, perguntas e atividades interativas com apoio da inteligência artificial.'),
('Lex AI', 'Escrita', 'Editor de texto inteligente que auxilia na criação, revisão, expansão e reorganização de conteúdos, facilitando a produção de materiais pedagógicos.'),
('LightPDF AI', 'Documentos', 'Plataforma que permite conversar com PDFs, resumir documentos, traduzir textos e extrair informações importantes utilizando IA.'),
('Liner AI', 'Pesquisa e estudos', 'Mecanismo de busca com IA que resume páginas da web, responde perguntas e organiza informações para pesquisas acadêmicas.'),
('Lovo AI', 'Síntese de voz', 'Ferramenta que transforma textos em narrações com vozes naturais, útil para audiolivros, videoaulas e recursos de acessibilidade.'),
('Luma AI', 'Geração de vídeos e 3D', 'Ferramenta que cria vídeos e modelos tridimensionais a partir de textos ou imagens, ideal para projetos de Ciências, História, Geografia e Artes.'),
('MagicSchool AI', 'Planejamento pedagógico', 'Plataforma desenvolvida exclusivamente para professores. Cria planos de aula, avaliações, rubricas, adaptações curriculares, feedbacks, comunicados e mais de 80 ferramentas voltadas ao trabalho docente.'),
('Mapbox AI tools', 'Geografia', 'visualização de dados geográficos.'),
('Mapify AI (antigo ChatMind)', 'Mapas mentais', 'Converte textos, vídeos, PDFs e páginas da internet em mapas mentais organizados automaticamente, facilitando o estudo e o planejamento.'),
('MathGPT (ou ChatGPT com foco matemático)', 'Matemática', 'explicação de conceitos e resolução guiada.'),
('MathGPTPro', 'Matemática', 'Assistente especializado em Matemática que resolve problemas, explica conceitos passo a passo e auxilia na elaboração de atividades e exercícios.'),
('Mentimeter AI', 'Apresentações interativas', 'Utiliza IA para criar apresentações, enquetes, quizzes e perguntas interativas, aumentando a participação dos estudantes durante as aulas.'),
('Microsoft Copilot', 'Assistente de IA', 'Assistente integrado ao Microsoft 365 que auxilia na elaboração de documentos, apresentações, planilhas, e-mails, pesquisas e planejamento pedagógico.'),
('Microsoft Designer', 'Design gráfico', 'Ferramenta de IA para criação de cartazes, apresentações, convites, postagens para redes sociais e materiais didáticos personalizados.'),
('Midjourney', 'Arte', 'criação artística visual avançada.'),
('Mindgrasp AI', 'Estudos e resumos', 'Ferramenta que analisa PDFs, vídeos, apresentações e áudios, produzindo resumos, flashcards, quizzes e respostas para facilitar a aprendizagem.'),
('Mizou AI', 'Chatbots educacionais', 'Plataforma que permite criar chatbots personalizados para responder dúvidas dos estudantes, simular diálogos e apoiar o ensino personalizado.'),
('Monica AI', 'Assistente de produtividade', 'Extensão baseada em IA que resume textos, responde perguntas, traduz conteúdos, cria e-mails e auxilia na organização do trabalho docente.'),
('Murf AI', 'Síntese de voz', 'Plataforma que transforma textos em narrações com vozes naturais em diversos idiomas, ideal para videoaulas, podcasts e recursos de acessibilidade.'),
('MyFitnessPal (IA de dieta e desempenho)', 'Educação Física', 'acompanhamento corporal.'),
('Napkin AI', 'Diagramas e infográficos', 'Transforma textos em diagramas, fluxogramas e infográficos automaticamente, facilitando a criação de materiais visuais para as aulas.'),
('Narrative BI', 'Análise de dados', 'Utiliza IA para transformar dados em relatórios narrativos fáceis de compreender, auxiliando gestores escolares e professores na interpretação de indicadores educacionais.'),
('NaturalReader AI', 'Leitura em voz alta', 'Converte textos em áudio com vozes naturais, promovendo acessibilidade para estudantes com deficiência visual, dislexia ou dificuldades de leitura.'),
('Neural Love', 'Imagens e restauração', 'Ferramenta de IA para restaurar fotografias antigas, aumentar resolução de imagens e colorizar fotos históricas, útil em projetos de História e Artes.'),
('Nolej AI', 'Criação de atividades', 'Plataforma educacional que transforma textos, vídeos e documentos em quizzes, flashcards, jogos e atividades interativas automaticamente.'),
('NotebookAI', 'Organização de estudos', 'Plataforma que organiza anotações, produz resumos, responde perguntas e auxilia na revisão de conteúdos utilizando inteligência artificial.'),
('NotebookLM (Google)', 'Pesquisa e organização', 'Assistente de IA do Google que analisa documentos enviados pelo professor, gera resumos, cria perguntas, explica conceitos e auxilia no planejamento de aulas com base em fontes confiáveis.'),
('Notion AI', 'Organização e produtividade', 'Recurso de IA integrado ao Notion que cria planos de aula, organiza projetos, resume textos, gera listas de tarefas e auxilia na produção de documentos pedagógicos.'),
('Numerade AI', 'Matemática e Ciências', 'Plataforma que oferece explicações em vídeo e resolução de problemas nas áreas de Matemática, Física, Química e Biologia, apoiando estudantes e professores.'),
('Nyota AI', 'Reuniões e organização', 'Assistente que grava, transcreve, resume reuniões e organiza tarefas automaticamente, sendo útil em encontros pedagógicos e planejamento escolar.'),
('Ocoya AI', 'Marketing e design', 'Plataforma que cria textos, imagens e postagens para redes sociais, podendo ser utilizada por escolas e professores na divulgação de projetos educacionais.'),
('OpenAI ChatGPT', 'Assistente educacional', 'IA conversacional que auxilia professores na elaboração de planos de aula, avaliações, sequências didáticas, projetos, adaptações curriculares, feedbacks e produção de materiais pedagógicos.'),
('OpenArt AI', 'Geração de imagens', 'Ferramenta que cria ilustrações, imagens e artes digitais a partir de comandos em texto, ideal para produção de recursos didáticos.'),
('OpenRead', 'Pesquisa científica', 'Plataforma que utiliza IA para localizar, resumir e analisar artigos científicos, facilitando revisões de literatura e pesquisas educacionais.'),
('OpenRouter', 'Integração de modelos de IA', 'Plataforma que permite acessar diferentes modelos de inteligência artificial em um único ambiente, sendo útil para pesquisadores, desenvolvedores e projetos educacionais avançados.'),
('Opus Clip AI', 'Edição de vídeos', 'Utiliza IA para transformar vídeos longos em pequenos clipes, facilitando a criação de conteúdos para aulas e redes sociais educacionais.'),
('Ora.ai', 'Criação de chatbots', 'Ferramenta que permite desenvolver chatbots personalizados sem necessidade de programação, útil para projetos educacionais e atendimento aos estudantes.'),
('Originality.ai', 'Verificação de textos', 'Plataforma que identifica possíveis conteúdos gerados por IA, verifica plágio e auxilia na análise da originalidade de produções escritas.'),
('Otio AI', 'Pesquisa acadêmica', 'Assistente de pesquisa que resume artigos, vídeos, PDFs e páginas da internet, organizando informações para estudos e produção científica.'),
('Otter.ai', 'Transcrição de áudio', 'Plataforma que grava, transcreve e resume reuniões, palestras e aulas automaticamente, facilitando registros pedagógicos e estudos.'),
('Padlet AI', 'Colaboração', 'Recurso de IA do Padlet que auxilia na criação de murais colaborativos, planos de aula, atividades, brainstormings e organização de projetos escolares.'),
('Perplexity AI', 'Pesquisa inteligente', 'Assistente de IA que responde perguntas utilizando fontes atualizadas da internet, apresentando referências e auxiliando em pesquisas acadêmicas e planejamento de aulas.'),
('Phi (Microsoft)', 'Modelo de linguagem', 'Família de modelos de IA da Microsoft voltada para geração de texto, programação e resolução de problemas, útil em projetos de tecnologia educacional.'),
('Photomath', 'Matemática', 'resolução passo a passo de problemas matemáticos.'),
('PhotoRoom AI', 'Edição de imagens', 'Plataforma que remove fundos, cria montagens e produz imagens profissionais para apresentações, atividades e materiais escolares.'),
('Pika', 'Geração de vídeos', 'Ferramenta de IA que cria vídeos curtos a partir de descrições em texto ou imagens, ideal para apresentações e recursos audiovisuais educativos.'),
('Pixlr AI', 'Edição de imagens', 'Editor de imagens com recursos de IA, como remoção de fundo, expansão de imagens, geração de elementos e melhorias automáticas.'),
('Playground AI', 'Geração de imagens', 'Plataforma para criar, editar e personalizar imagens utilizando inteligência artificial, útil para cartazes, ilustrações e materiais didáticos.'),
('Poe (Quora)', 'Agregador de IAs', 'Plataforma que reúne diversos modelos de inteligência artificial em um único ambiente, permitindo comparar respostas e explorar diferentes assistentes virtuais.'),
('PopAI', 'Apresentações e documentos', 'Assistente de IA que cria apresentações, resume PDFs, responde perguntas e organiza conteúdos para estudos e planejamento pedagógico.'),
('PromptPerfect', 'Engenharia de prompts', 'Ferramenta que melhora automaticamente prompts para diferentes modelos de IA, ajudando professores a obter respostas mais precisas e completas.'),
('Q-Chat (Quizlet)', 'Tutor inteligente', 'Assistente de IA do Quizlet que conduz conversas educativas, faz perguntas, oferece feedback e auxilia os estudantes durante o processo de aprendizagem.'),
('Qlik AutoML', 'Análise de dados', 'Ferramenta de IA para análise preditiva e visualização de dados, podendo ser utilizada em pesquisas educacionais, gestão escolar e projetos de ciência de dados.'),
('Question AI', 'Apoio aos estudos', 'Assistente inteligente que explica exercícios, responde dúvidas e apresenta resoluções comentadas em diferentes áreas do conhecimento.'),
('QuestionWell', 'Criação de questões', 'Plataforma que gera questões de múltipla escolha, perguntas abertas e atividades avaliativas em poucos segundos utilizando inteligência artificial.'),
('Quick Creator AI', 'Produção de conteúdo', 'Plataforma que cria textos, páginas, materiais educativos e conteúdos digitais utilizando inteligência artificial.'),
('QuickMagic AI', 'Animação', 'Ferramenta que utiliza IA para criar animações a partir de vídeos, podendo ser aplicada em projetos educacionais de Artes, Tecnologia e Produção Audiovisual.'),
('QuillBot', 'Escrita e revisão', 'Assistente de IA que reescreve textos, corrige gramática, resume documentos, traduz conteúdos e melhora a clareza da escrita, sendo útil na produção de materiais pedagógicos.'),
('Quizizz AI', 'Avaliação e gamificação', 'Utiliza IA para criar quizzes, provas, atividades e lições interativas automaticamente a partir de textos, PDFs ou temas informados pelo professor.'),
('Quso.ai', 'Produção de vídeos', 'Plataforma de IA que transforma vídeos longos em pequenos clipes, gera legendas automáticas e cria conteúdos para redes sociais e educação.'),
('Qwen (Alibaba Cloud)', 'Modelo de linguagem', 'Família de modelos de IA generativa desenvolvida pela Alibaba, utilizada para produção de textos, programação, tradução e desenvolvimento de aplicações educacionais.'),
('ReadSpeaker', 'Acessibilidade', 'Ferramenta que converte textos em voz natural, favorecendo a inclusão de estudantes com deficiência visual, dislexia ou dificuldades de leitura.'),
('ReadTheory AI', 'Compreensão leitora', 'Plataforma adaptativa que utiliza IA para personalizar atividades de leitura, interpretar o desempenho dos estudantes e ajustar automaticamente o nível de dificuldade dos textos.'),
('Recraft AI', 'Design gráfico', 'Ferramenta especializada na criação de ilustrações vetoriais, ícones, infográficos e materiais visuais para apresentações e atividades escolares.'),
('Remove.bg', 'Edição de imagens', 'Utiliza IA para remover automaticamente o fundo de imagens, facilitando a criação de cartazes, apresentações e recursos didáticos.'),
('Renderforest AI', 'Apresentações e vídeos', 'Ferramenta que cria apresentações, animações, vídeos, logotipos e materiais gráficos utilizando inteligência artificial.'),
('ResearchRabbit', 'Pesquisa científica', 'Plataforma inteligente que organiza artigos científicos em mapas de conhecimento, identificando conexões entre autores, pesquisas e referências bibliográficas.'),
('Rewind AI', 'Produtividade', 'Assistente que registra atividades realizadas no computador, permitindo recuperar informações, localizar documentos e revisar conteúdos anteriormente acessados.'),
('Rewordify', 'Leitura', 'simplificação de textos complexos.'),
('Rosebud AI', 'Desenvolvimento de jogos', 'Plataforma que utiliza IA para criar jogos, personagens e experiências interativas, sendo útil em projetos de programação e gamificação na educação.'),
('Runway ML', 'Geração e edição de vídeos', 'Plataforma de IA para criar vídeos a partir de textos, remover objetos, substituir fundos, gerar animações e produzir materiais audiovisuais educativos.'),
('Rytr', 'Produção de textos', 'Assistente de escrita que gera planos de aula, atividades, e-mails, resumos, descrições e diversos tipos de textos com auxílio da IA.'),
('SchoolAI', 'Assistente educacional', 'Plataforma desenvolvida para professores que cria planos de aula, atividades, rubricas, feedbacks personalizados e experiências de aprendizagem com apoio da IA.'),
('SciSpace AI', 'Pesquisa científica', 'Assistente que explica artigos científicos, responde perguntas sobre pesquisas e simplifica conceitos complexos para professores e estudantes.'),
('Scisummary', 'Resumos científicos', 'Utiliza IA para resumir artigos científicos e destacar seus principais resultados, apoiando pesquisas acadêmicas e formação continuada de professores.'),
('Scribbr AI', 'Escrita acadêmica', 'Plataforma que auxilia na revisão de textos, correção gramatical, detecção de plágio e formatação de trabalhos científicos.'),
('SlidesAI.io', 'Apresentações', 'Converte textos em apresentações organizadas automaticamente, economizando tempo na preparação de aulas e palestras.'),
('Sora (OpenAI)', 'Geração de vídeos', 'Modelo de IA capaz de transformar descrições em vídeos realistas, permitindo criar animações e recursos audiovisuais para o ensino.'),
('Speechify', 'Leitura em voz alta', 'Ferramenta que converte textos em áudio com vozes naturais, favorecendo acessibilidade e diferentes estilos de aprendizagem.'),
('Storybird AI', 'Alfabetização', 'Criação de histórias curtas ilustradas para leitura guiada, estímulo à compreensão de narrativa e incentivo à produção textual inicial com apoio visual.'),
('Study Fetch AI', 'Estudos personalizados', 'Plataforma que transforma PDFs, apresentações, vídeos e anotações em resumos, flashcards, quizzes e planos de estudo personalizados.'),
('Suno AI', 'Geração de músicas', 'Ferramenta que cria músicas completas com letra, melodia e voz a partir de comandos em texto, ideal para projetos interdisciplinares e atividades criativas.'),
('Symbolab', 'Matemática', 'cálculo algébrico e explicações detalhadas.'),
('Synthesia', 'Avatares e videoaulas', 'Cria vídeos com apresentadores virtuais que narram conteúdos em diversos idiomas, facilitando a produção de videoaulas sem necessidade de gravação.'),
('TalkPal AI', 'Aprendizagem de idiomas', 'Assistente de conversação com IA que ajuda estudantes a praticar idiomas por meio de diálogos interativos e feedback imediato.'),
('TeacherMatic', 'Planejamento docente', 'Plataforma voltada para professores que gera planos de aula, atividades, avaliações, objetivos de aprendizagem e recursos pedagógicos com IA.'),
('TeachMateAI', 'Assistente educacional', 'Ferramenta que auxilia professores na criação de materiais didáticos, feedbacks, comunicados, atividades diferenciadas e planejamento pedagógico.'),
('TensorFlow', 'Desenvolvimento de IA', 'Biblioteca de código aberto do Google para criação de modelos de inteligência artificial, usada em projetos educacionais de programação e ciência de dados.'),
('Text Blaze AI', 'Produtividade', 'Ferramenta de automação que permite criar atalhos de texto para respostas rápidas, feedbacks e comunicações frequentes de professores.'),
('Timely AI', 'Gestão de tempo', 'Ferramenta que rastreia automaticamente o tempo gasto em tarefas e ajuda professores a organizar produtividade e planejamento.'),
('TinyWow AI', 'Ferramentas educacionais', 'Plataforma com diversos recursos de IA para PDF, imagens, textos e vídeos, como conversão, resumo, edição e geração de conteúdo.'),
('Tome AI', 'Apresentações', 'Cria apresentações, narrativas visuais e documentos interativos automaticamente a partir de textos, ideias ou comandos simples.'),
('TTSMaker', 'Síntese de voz', 'Converte textos em áudio com vozes naturais em vários idiomas, útil para acessibilidade e produção de materiais educativos em áudio.'),
('Turnitin AI', 'Escrita acadêmica', 'Sistema de verificação de originalidade que detecta plágio e analisa textos produzidos por IA, auxiliando na integridade acadêmica.'),
('Uberduck AI', 'Voz e áudio', 'Gera vozes sintéticas, narrações e músicas com IA, podendo ser usado em videoaulas e projetos criativos.'),
('Udio AI', 'Geração de música', 'Plataforma que cria músicas completas com letras e melodia a partir de comandos em texto, ótima para atividades interdisciplinares.'),
('Uizard AI', 'Design e prototipagem', 'Converte desenhos, ideias e textos em interfaces digitais, aplicativos e layouts interativos, útil para projetos escolares e ensino de tecnologia.'),
('Unboring AI (Reface AI)', 'Criação de conteúdo criativo', 'Permite criar vídeos e imagens divertidas com IA, sendo útil para projetos criativos e engajamento em sala de aula.'),
('Undetectable AI', 'Reescrita de texto', 'Reescreve conteúdos gerados por IA para torná-los mais naturais, sendo importante em discussões sobre ética e uso responsável da tecnologia.'),
('Unschooler AI', 'Aprendizagem personalizada', 'Cria trilhas de aprendizagem personalizadas e guiadas, ajudando estudantes a aprender no próprio ritmo.'),
('Unscreen', 'Edição de vídeo/imagem', 'Remove automaticamente o fundo de vídeos e imagens, facilitando a criação de conteúdos educativos mais profissionais.'),
('Upscale.media', 'Edição de imagens', 'Utiliza IA para melhorar a qualidade e resolução de imagens, ideal para materiais didáticos e recursos visuais.'),
('Upword AI', 'Pesquisa e resumos', 'Resume artigos, vídeos e documentos, organizando informações para facilitar estudos e planejamento docente.'),
('UserWay AI', 'Acessibilidade digital', 'Ferramenta que adapta sites e conteúdos digitais para acessibilidade, melhorando contraste, leitura e navegação para alunos com necessidades especiais.'),
('Vana AI', 'IA pessoal', 'Cria assistentes personalizados baseados em dados do usuário, podendo apoiar organização de estudos e produtividade docente.'),
('VEED.io AI', 'Edição de vídeo', 'Plataforma que usa IA para criar, editar e legendar vídeos automaticamente, facilitando produção de aulas e conteúdos digitais.'),
('VidIQ AI', 'YouTube e educação digital', 'Ferramenta que ajuda na criação, otimização e análise de vídeos no YouTube, útil para professores criadores de conteúdo.'),
('Vidnoz AI', 'Vídeos com avatares', 'Cria vídeos com avatares falantes a partir de texto, ideal para videoaulas, explicações e conteúdos educativos.'),
('Viggle AI', 'Animação', 'Permite animar personagens e imagens a partir de vídeos, útil para projetos criativos e educativos.'),
('Visme AI', 'Apresentações e design', 'Cria apresentações, infográficos, relatórios e materiais visuais com ajuda de inteligência artificial.'),
('Vocalremover.org AI', 'Áudio e música', 'Separa voz e instrumental de músicas, útil para atividades musicais e projetos escolares.'),
('Voiceflow AI', 'Chatbots', 'Plataforma para criar assistentes virtuais e chatbots educativos sem necessidade de programação.'),
('VoxScript AI', 'Pesquisa e transcrição', 'Extrai e resume informações de vídeos, especialmente do YouTube, ajudando no estudo de conteúdos educativos.'),
('Vrew AI', 'Edição de vídeo', 'Editor de vídeo com IA que gera legendas automáticas e facilita cortes e organização de videoaulas.'),
('WeVideo AI', 'Edição de vídeo', 'Plataforma de criação e edição de vídeos com IA, permitindo produzir videoaulas, projetos escolares e conteúdos interativos.'),
('Whisper (OpenAI)', 'Transcrição de áudio', 'Sistema de IA que transforma áudio em texto com alta precisão, útil para transcrever aulas, entrevistas e vídeos educativos.'),
('Wisecut AI', 'Edição automática de vídeo', 'Remove pausas, erros e melhora automaticamente vídeos educativos e gravações de aula.'),
('Woebot AI', 'Bem-estar emocional', 'Chatbot baseado em IA voltado ao apoio emocional e psicológico, podendo ser usado como referência em projetos de educação socioemocional.'),
('Wolfram Alpha', 'Matemática', 'resolução avançada e explicações conceituais.'),
('Wolfram Alpha AI', 'Matemática e ciência', 'Motor de conhecimento que resolve cálculos, equações, problemas científicos e gera explicações detalhadas passo a passo. Muito útil para Matemática e Ciências.'),
('Wonder AI', 'Geração de imagens', 'Cria imagens artísticas a partir de texto, útil para ilustrações e materiais visuais escolares.'),
('Wondershare Filmora AI', 'Edição de vídeo', 'Editor de vídeo com recursos de IA como legendas automáticas, remoção de ruído e geração de roteiros.'),
('Wordtune', 'Língua Portuguesa', 'melhora de clareza e estilo de escrita.'),
('Wordtune AI', 'Escrita e revisão', 'Ferramenta que reescreve textos, melhora clareza, ajusta tom e ajuda na produção de atividades, relatórios e materiais pedagógicos.'),
('Wordwall AI', 'Gamificação', 'Cria atividades interativas, jogos educativos, quizzes e dinâmicas para sala de aula.'),
('WriterZen AI (modo Z-index SEO)', 'Escrita e SEO', 'Ferramenta de organização de conteúdo e otimização de textos, útil para produção de materiais educativos digitais.'),
('Writesonic AI', 'Produção de conteúdo', 'Gera textos, atividades, planos de aula, e-mails e materiais educativos de forma automatizada.'),
('X (Twitter) + AI Tools', 'Comunicação e informação', 'A plataforma X integra recursos de IA para resumo de conteúdos, análise de tendências e apoio à criação de textos e postagens educativas.'),
('X.ai (antigo assistente de agenda)', 'Produtividade', 'IA focada em organização de agenda e agendamento automático de reuniões e tarefas (base conceitual ainda usada em ferramentas modernas).'),
('xAI (Grok)', 'Assistente de IA', 'Empresa de inteligência artificial criada por Elon Musk. Seu modelo Grok é um assistente conversacional que ajuda em pesquisas, explicações e criação de conteúdos educativos.'),
('X-Design AI (referência criativa)', 'Design digital', 'Plataformas com nome “X-Design” utilizam IA para criação de layouts, imagens e materiais visuais para educação e marketing.'),
('Xenon AI', 'Pesquisa e automação', 'Plataforma de IA usada para análise de dados, automação de processos e apoio a pesquisas acadêmicas e tecnológicas.'),
('Xenon Stack AI', 'Análise de dados', 'Plataforma que usa IA para análise de dados, automação de sistemas e suporte a decisões, útil em projetos educacionais de tecnologia.'),
('Ximilar AI', 'Visão computacional', 'Ferramenta de IA especializada em reconhecimento de imagens, categorização visual e análise de objetos — útil em projetos de tecnologia e ciência.'),
('Xno AI (experimental)', 'Desenvolvimento de IA', 'Projeto experimental voltado para criação e testes de modelos de inteligência artificial em ambientes de pesquisa.'),
('Xpert AI (educacional)', 'Tutoria inteligente', 'Assistente de aprendizagem que auxilia estudantes com explicações e resolução de dúvidas em diversas áreas do conhecimento.'),
('Xtract AI', 'Extração de dados', 'Ferramenta de IA que extrai informações de documentos, PDFs e páginas da web, facilitando pesquisa e estudo.'),
('Yandex GPT', 'Modelo de linguagem', 'IA russa de linguagem natural usada para geração de textos, respostas e apoio em pesquisas e tradução.'),
('Yellow.ai', 'Chatbots', 'Plataforma de criação de assistentes virtuais e chatbots inteligentes usados em educação, atendimento e automação de respostas.'),
('YesChat AI', 'Assistente de IA', 'Plataforma que integra modelos de IA para conversação, geração de textos, resumos e apoio ao estudo.'),
('Yomu AI', 'Escrita acadêmica', 'Assistente de IA voltado para redação científica, artigos, revisão de textos e apoio a pesquisas acadêmicas.'),
('Yoodli AI', 'Comunicação e oratória', 'Treina fala e apresentações, fornecendo feedback automático sobre clareza, fluência e desempenho — útil para apresentações de alunos.'),
('You.com AI', 'Pesquisa inteligente', 'Motor de busca com IA que responde perguntas, resume conteúdos e ajuda na pesquisa de materiais educativos com fontes organizadas.'),
('YouCam AI', 'Imagem e vídeo', 'Ferramenta de IA para edição de imagens, vídeos e filtros criativos, útil em projetos escolares e produções multimídia.'),
('YouLearn AI', 'Educação personalizada', 'Plataforma que transforma conteúdos em resumos, quizzes e materiais de estudo personalizados para estudantes.'),
('YourAI (plataformas personalizadas)', 'IA personalizada', 'Conjunto de ferramentas que permitem criar assistentes de IA personalizados para ensino, estudo e produtividade.'),
('YouTube + AI (Studio AI)', 'Educação e mídia', 'O YouTube utiliza IA para recomendações, legendas automáticas e ferramentas de criação no YouTube Studio, auxiliando professores criadores de conteúdo.'),
('Zapier AI', 'Automação', 'Plataforma que conecta aplicativos e automatiza tarefas com IA, como enviar e-mails, organizar planilhas e integrar ferramentas educacionais.'),
('Zebracat AI', 'Criação de vídeos', 'Plataforma que transforma textos em vídeos automaticamente com narração e recursos visuais, útil para videoaulas e conteúdos digitais.'),
('Zencastr AI', 'Podcast e áudio', 'Plataforma que grava, edita e melhora automaticamente áudios e podcasts educativos com inteligência artificial.'),
('ZeroGPT', 'Detecção de IA', 'Ferramenta que identifica textos gerados por inteligência artificial, útil em avaliações escolares e integridade acadêmica.'),
('Zeus AI (modelos e pesquisas)', 'Inteligência artificial', 'Nome usado em alguns projetos e modelos experimentais de IA aplicados à análise de dados e automação.'),
('ZMO.AI', 'Geração de imagens', 'Ferramenta de IA para criação de imagens, avatares e artes digitais usadas em materiais educativos e criativos.'),
('Zoom AI Companion', 'Reuniões e ensino online', 'Assistente de IA do Zoom que resume reuniões, cria atas automáticas e ajuda na organização de aulas online.'),
('Zotero AI', 'Pesquisa acadêmica', 'Ferramenta de gerenciamento de referências que organiza citações, PDFs e fontes acadêmicas, facilitando trabalhos científicos e projetos escolares.'),
('Zyro AI (Hostinger AI)', 'Criação de sites', 'Plataforma que cria sites automaticamente com IA, podendo ser usada em projetos escolares e portfólios digitais.');
